# original configuration here: https://github.com/sproogen/modern-resume-theme/blob/master/_config.yml
# example: https://sproogen.github.io/modern-resume-theme/
favicon: images/favicon.ico

# Content configuration version
version: 2


# Personal info
name: Charles Mueller
title: Analytics Engineer
# email: <redacted>

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  crmueller100
linkedin_username: charles-mueller

# About Section
about_title: About Me
about_profile_image: linkedin_profile.png
about_content: | # this will include new lines to allow paragraphs
  My name is Charles and welcome to my website! I created this page as a place to share my professional journey, showcase some of my projects, and give folks an opportunity to connect.

  I'm currently an Analytics Engineer [Aclaimant](https://aclaimant.com/). Outside of my full-time job, I'm passionate about Machine Learning, Software Engineering, and learning about cloud-based infrastructure. I stay up-to-date with the market by subscribing to a multitude of newsletters and blogs, so let me know if you have anyone you think I should add to my feed!

  My strongest proficiencies are in <mark>Python</mark>, <mark>SQL</mark>, and <mark>Data Engineering</mark>.


    
# Software engineer mindset

# I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Chicago Traffic Violations
        link: github.com/crmueller100/chicago-traffic-violations
        link_text: View it on GitHub
        quote: >
          "But I'm sure I came to a complete stop! Oh wait, they sent a video..."
        description: | # this will include new lines to allow paragraphs
          I did some analysis of Chicago's camera-based ticketing system using their [public data portal](https://data.cityofchicago.org/).
          It was a simple project that helped to keep my data analysis skills fresh, as well as uncover insights into citation patterns, particularly regarding ticket hotspots and temporal/seasonal variations.
          Its findings offer insights for residents to stay safe and save money.

      - layout: top-middle
        title: Horsies
        link: github.com/crmueller100/horsies
        link_text: View it on Github
        quote: >
          And they're off!
        description: | # this will include new lines to allow paragraphs
          This was a quick project I made to settle an argument among my friends. "Horsies" is a luck-based board game that involves cards, dice, and probability. 
          After debating with them about which starting position has the highest chance of victory, I decided to simply brute force a solution. 
          Even when presented with my numerical analysis, many still remain loyal to their gut instinct. I suppose that's gambling for you.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Aclaimant
        link: aclaimant.com
        link_text: aclaimant.com
        sub_title: Analytics Engineer
        caption: May 2018 - Present
        quote: >
          Aclaimant. Not Acclaimant. Not A-Claimant. 
        description: | # this will include new lines to allow paragraphs
          Aclaimant was only 15 people when I joined. I was privileged to see it grow to more than double the size.
          As anyone who has worked in a startup can attest to, I take ownership over many responsibilities that expand beyond the scope of my job title.
          I frequently engage in data engineering, data analytics, business intelligence reviews, correspond and/or meet with our customers, and am always open as a point of contact to all other departments for ad hoc requests.

      # - layout: left
      #   title: Marquette Partners
      #   link: https://marquettepartners.squarespace.com/
      #   link_text: mqplp.com
      #   sub_title: Options Trader
      #   caption: July 2015 - September 2017
      #   quote: >
      #     Buy low [volatility], sell high [volatility]
      #   description: | # this will include new lines to allow paragraphs
      #     Aclaimant was only 15 people when I joined. I was privileged to see it grow to more than double the size.
      #     As anyone who has worked in a startup can attest to, I take ownership over many responsibilities that expand beyond the scope of my job title.
      #     I frequently engage in data engineering, data analytics, business intelligence reviews, correspond and/or meet with our customers, and am always open as a point of contact to all other departments for ad hoc requests.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Georgia Institute of Technology
        caption: 2021 - 2023
        sub_title: Master of Science in Computer Science
        quote: >
          &#127925 I'm a Ramlin' Wreck from Georgia Tech...&#127925
        description: | # this will include new lines to allow paragraphs
          Completing a Master's in Computer Science while balancing a full-time job was no simple task, but I'm glad I did it. I took classes from various disciplines within the field of Computer Science, but my specialization was in Machine Learning.
          GA Tech's program was loaded with hands-on experience, reading technical literature, and learning about the theory and mathematics behind various Machine Learning, Deep Learning, and Reinforcement Learning techniques.

      - layout: left
        title: University of Illinois at Urbana-Champaign
        caption: 2012 - 2015
        sub_title: Bachelor of Science in Engineering Mechanics
        quote: >
          I-L-L
        description: | 
          I couldn't be happier with my decision to pursue am undergraduate degree in Engineering Mecahnics (referred to some as Theoretical and Applied Mechanics (TAM)). As an uncertain teenager trying to choose a career path, a major in Engineering Mechanics facilitated valuable exposure to a broad range of engineering sub-disciplines.
          The program's flexibility allowed me to focus on Computational Mechanics during my senior year, which sparked a passion for computational methods.
          This would eventually blossom into a devotion to the fields of data science and software engineering.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      In addition to my career and professional life, I enjoy spending time in the following activities:
        - Playing piano
        - Studying chess
        - Exercising
        - Playing 16" softball

# Footer
# footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

github: [metadata]
